### ISSUE TITLE
Incorrect bonds during parsing form `connect_via_residue_names()`

### ISSUE THREAD

**Issue by BradyAJohnston** [biotite-dev/biotite#638] opened 2024-08-22 10:00 UTC
When parsing some small molecules as `.pdb` files, extra incorrect bonds are being found by biotite. See [this issue](https://github.com/BradyAJohnston/MolecularNodes/issues/548) for more details for Molecular Nodes. 

![](https://private-user-images.githubusercontent.com/175439302/348358007-c244d14b-5324-4c94-8b92-cc2b25cf6be1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjA3ODksIm5iZiI6MTcyNDMyMDQ4OSwicGF0aCI6Ii8xNzU0MzkzMDIvMzQ4MzU4MDA3LWMyNDRkMTRiLTUzMjQtNGM5NC04YjkyLWNjMmIyNWNmNmJlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwOTU0NDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGZkNmM0ZjgxMjJmMDMyNDZlYzRmY2U3OGE5MDkxYzdlMjE1NGFlNzhkM2I2ZWU1ZmRmMThmZWM0OTY0YzhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OUdKQyyOwKkceLRaRHiaF9tzdQFq14A7sPoGI73xPTk)

I've had a poke around and tracked it to this line: https://github.com/biotite-dev/biotite/blob/0404084283765baef765cc869d86ee07a898d82f/src/biotite/structure/io/pdb/file.py#L546

Which is incorrectly creating bonds between atoms that are assumed to be part of a residue but are not.

Before that call, the correct list of bonds are found, but after that call there are extra bonds between atoms that should not be bonded.

**Comment by padix-key** [comment] 2024-08-22 11:49
Hi, I roughly checked the erroneous cases in https://github.com/BradyAJohnston/MolecularNodes/issues/548. It seems this is caused by the PDB files using different residue names than in the official PDB files, i.e. in the Chemical Component Dictionary:

Biotite searches for the residues in the CCD and finds an entry. However this entry does not actually represent the molecule in the PDB file. Hence, wrong atoms are connected, as these are the atoms that would be connected in the molecule from the CCD that has accidentally the same name.

To fix this Biotite could only resort to the CCD for standard residues, as these are not present in `CONECT` records connect standard residues (amino acids and nucleotides). From the PDB spec:

> CONECT records are present for:
  - Intra-residue connectivity within  non-standard (HET) residues (excluding water).
  - Inter-residue connectivity of HET  groups to standard groups (including water) or to other HET groups. 
  - Disulfide bridges specified in the  SSBOND records have corresponding records.

This would fix the problem of @julioarvellos, but not the one of @rbdavid as his PDB file does not contain `CONECT` records. Hence, Biotite has no means to know which atoms should be connected. Here it could work to infer the bonds by distance (but I do not know if this is reasonable to be implemented by MolecularNodes):

```python
atoms = pdb_file.get_structure(include_binds=False)
atoms = struc.connect_via_distances(atoms)
```

**Comment by BradyAJohnston** [comment] 2024-08-22 13:07
Thanks for looking into it! I am unsurprised that it is more malformed / incorrect PDB files being the culprit than biotite getting it wrong.

I could potentially also add a check myself to remove bonds / edges that are over a certain cutoff distance.

**Comment by Croydon-Brixton** [comment] 2024-09-03 18:44
@padix-key would adding the `alt_atom_id` in the CCD help us address this? We could then (1) first try to connect according to the standard atom names and if that fails (2) fallback to the alternative atom names?

**Comment by padix-key** [comment] 2024-09-04 07:26
If I am not wrong, the problem is not that these PDB files use other alternative atom naming, but the wrong residue names, i.e. they use the name `XYZ` for a molecule that the CCD names `ABC`. Hence, The bonds for `XYZ` are added to the molecule, while the molecule would require the bonds from `ABC`.

**Comment by BradyAJohnston** [comment] 2024-09-06 02:31
I'm assuming these example files that I was provided with came from some simulation packages that are pretty notorious for abusing the PDB format in a whole bunch of different ways (which I'm sure would also include naming conventions), so I don't know if there is actually anything to actually be done here.

**Comment by padix-key** [comment] 2024-09-07 17:22
One could set `custom_bond_dict` in [`connect_via_residue_names()`](https://www.biotite-python.org/latest/apidoc/biotite.structure.connect_via_residue_names.html) and restrict them to amino acid and nucleotides.

However, I did some further research and did not find a trustful source which other residues the PDB deem 'standard'. Hence, I fear that this potential 'fix' could break other cases. Hence, I would rather refrain from changing the behavior here. As you @BradyAJohnston seem to have the same opinion, I would close this issue.

For your users I would propose, they rename the faulty residue names in their PRB files to the correct ones or to ones that are not inside the CCD at all, e.g. a name containing a special characters such as an `_`.

**Closed** 2024-09-07 17:23 UTC
Labels: bug
